name: Development

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: |
          composer install -o

      - name: Sync
        env:
          dest: '${{ secrets.SSH_USER }}@tallgrass.church:/dev.tallgrass.church/'
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /web/sites/*/settings*.php \
            --exclude /web/sites/*/services*.yml \
            --exclude /web/sites/*/files/ \
            --exclude /web/sites/*/private/ \
            ./ ${{ env.dest }}
